### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by amadeu01** [scana/subscriptions-leak-example#1]
Hi! Thanks for the article.
I have one question. For the LeakingPresenter, if on the “MovieSuggestionViewImpl” when you call “presenter.destroy” on

```java
@Override 
protected void onDetachedFromWindow() { 
    presenter.destroy(); 
    super.onDetachedFromWindow(); 
}
```

On your code:

https://github.com/scana/subscriptions-leak-example/blob/282e6caa22e422f5cde52ac4c9d7080aea9f9998/app/src/main/java/me/scana/subscriptionsleak/MovieSuggestionViewImpl.java#L44-L48

You can find that `presenter.destroy()` here:

https://github.com/scana/subscriptions-leak-example/blob/282e6caa22e422f5cde52ac4c9d7080aea9f9998/app/src/main/java/me/scana/subscriptionsleak/LeakingPresenter.java#L61-L65

If you also atribute null to presenter, like:

```java
@Override 
protected void onDetachedFromWindow() {
    presenter.destroy();
    super.onDetachedFromWindow();
    presenter = null;
}
```

Would still exist memory leak? As I understood, the problem is that the presenter still hold some reference to the View. However, if there is no reference to the presenter, then It can be garbage collected and so the View.
Am I write?

**Comment by scana** [comment]
Oh my god, I am so sorry @amadeu01 - I have no idea how I managed to not see your issue.
You probably have already figured this out all by yourself, but I answer just for anybody else with a similar problem.

Yes, if you nullify your presenter reference, the memory leak will be gone. The case that I described was all about still being able to keep a reference to a presenter (e.g. for caching purposes or something).

Please feel free to reopen this issue if you'll have any follow-up question.
